# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 15:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 14, 15, 2, 46, 271712, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
